#!/usr/bin/env python3

import os, sys, subprocess
from PIL import Image

term_width = int( subprocess.check_output(['tput', 'cols']) )
term_height = int( subprocess.check_output(['tput', 'lines']) )

for infile in sys.argv[1:]:

    im = Image.open(infile)

    # resize the image to the terminal's width / height, preserving the image's ratio
    im.thumbnail([term_width, term_height], Image.ANTIALIAS)

    # get the resized image's width and height
    width, height = im.size

    for y in range(1, height):
        for x in range(0, width):

            # sets background or "first" y-axis pixel
            r, g, b = im.getpixel((x, y-1))
            background = "\033[48;2;" + str(r) + ";" + str(g) + ";" + str(b) + "m"

            # sets foreground or "second" y-axis pixel
            r, g, b = im.getpixel((x, y))
            foreground = "\033[38;2;" + str(r) + ";" + str(g) + ";" + str(b) + "m"

            print (background + foreground + u'\u2584' + u'\u2584', end='')

        y += 1
        print ("")
